DROP TABLE SHIPMENTS;
DROP SEQUENCE TRANSACTION_SEQ;

CREATE TABLE SHIPMENTS
( ID NUMBER,
  SENDER_NAME VARCHAR2(25),
  SENDER_ADDRESS VARCHAR2(25),
  RECIPIENT_NAME VARCHAR2(25),
  RECIPIENT_ADDRESS VARCHAR2(25),
  KILO NUMBER,
  AMOUNT NUMBER,
  SHIP_DATE VARCHAR2(15),
  SHIP_TIME VARCHAR2(15),
  BATCH NUMBER);

CREATE SEQUENCE TRANSACTION_SEQ
  START WITH 1
  INCREMENT BY 1;
  
CREATE OR REPLACE TRIGGER T_TRANSACTION
  BEFORE INSERT ON SHIPMENTS
  FOR EACH ROW
  BEGIN
    :NEW.ID := TRANSACTION_SEQ.NEXTVAL;
    :NEW.SHIP_DATE := TO_CHAR(SYSDATE, 'FXDD-MON-YYYY');
    :NEW.SHIP_TIME := TO_CHAR(SYSDATE, 'HH24:MI');
  END;